[build]
rustflags = [
  "-C", "link-arg=-fuse-ld=lld",
]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
  "-C", "link-arg=-fuse-ld=/usr/bin/mold",
]

[doc]
browser = "/mnt/c/Program Files/Google/Chrome/Application/chrome.exe"
